const U=(id,title,depth,summary,concepts,challenge,evidence)=>({id,title,depth,summary,concepts,challenge,evidence});
const M=(id,title,summary,why,legacyTopicIds,prerequisites,resourceRefs,units,curriculumReviewEveryDays=120)=>({id,title,summary,why,legacyTopicIds,prerequisites,resourceRefs,curriculumReviewEveryDays,lastReviewed:'2026-08-21',units});
const caseUnit=(id,title,depth,concepts)=>U(`lab-${id}`,`Design Lab: ${title}`,depth,'Complete architecture case: requirements, estimates, API/data model, architecture, failure analysis, security, observability, cost and evolution.',concepts,`Design ${title} at initial scale, then revise it for 100x scale plus a major failure, regulatory or product constraint.`,'Design doc + diagrams + capacity model + failure table + architecture review notes.');

const systemDesign={id:'system-design',phase:5,order:13,title:'System Design & Architecture Design Lab',summary:'Turn engineering building blocks into complete systems, then evolve them under scale, failure, product and organizational pressure.',modules:[
M('design-method','System design reasoning method','Turn ambiguous product goals into testable architecture decisions.','System design is structured reasoning, not memorized diagrams.',['system-design-method','nfr-architecture'],['quality-attributes','capacity-queueing'],['ddia','google-sre','gcp-arch','aws-wa'],[
U('requirements-scope','Requirements, scope & invariants','deep','Separate user journeys, business invariants and non-goals before choosing components.',['functional requirements','actors','critical journeys','business invariants','scope','non-goals','assumptions','unknowns'],'Take a vague request for a team-chat product and write the minimum architecture-driving requirements.','One-page scope with actors, invariants, non-goals and unresolved questions.'),
U('nfr-quantification','Quantify non-functional requirements','architect','Translate fast, scalable, secure and reliable into measurable targets.',['SLO','p50/p95/p99','throughput','availability','durability','RPO','RTO','consistency','data residency','cost envelope'],'Define NFRs for consumer chat, a payments ledger and internal analytics; explain why the targets differ.','Quality-attribute table with metrics and rationale.'),
U('design-loop','Architecture design loop','architect','Iterate requirements → estimates → contracts → data → components → failures → validation.',['requirements','capacity','API','data model','component boundaries','data flow','failure modes','security','observability','cost','rollout'],'Design the same notification platform twice, once prematurely and once using the full loop.','Design checklist plus before/after architecture review notes.')],90),
M('estimation','Back-of-the-envelope estimation & capacity models','Estimate load and storage well enough to reject impossible designs and locate bottlenecks.','Architecture changes when traffic shape or data volume changes by orders of magnitude.',['system-design-method','performance-capacity'],['design-method'],['google-sre','brendan-gregg','ddia'],[
U('traffic-estimation','Traffic, concurrency & bandwidth estimation','deep','Translate DAU/MAU and journeys into requests, concurrent connections and network load.',['DAU','peak factor','QPS','read/write ratio','concurrency','connection duration','fan-out','bandwidth'],'Estimate chat traffic for 10M DAU with presence and typing indicators.','Calculation sheet with assumptions and sensitivity ranges.'),
U('storage-estimation','Storage, retention & growth estimation','deep','Model logical data, indexes, replicas, logs and retention rather than row size alone.',['object count','bytes per object','index overhead','replication factor','retention','growth rate','backup','event log'],'Estimate five-year storage for messages, attachments and search indexes.','Storage model separating primary, replicated, indexed and archival data.'),
U('capacity-breakpoints','Capacity breakpoints & bottleneck hypotheses','architect','Predict when a design must change before benchmarking validates it.',['CPU','memory','IOPS','network','connection limits','DB pool','queue depth','hot partition','headroom'],'Identify which component fails first at 1x, 10x and 100x load for a read-heavy SaaS API.','Breakpoint table with proposed experiments.')],90),
M('building-blocks','System design building blocks','Choose edge, compute, data, cache, messaging and coordination primitives based on constraints.','Most design questions are compositions of a finite set of primitives.',[],['design-method','distributed-fundamentals'],['ddia','gcp-arch','aws-wa','eip'],[
U('edge-traffic','Edge, DNS, CDN, proxy & load balancing','deep','Understand where traffic is terminated, routed, cached and protected.',['DNS','CDN','L4 LB','L7 LB','reverse proxy','API gateway','WAF','TLS termination','connection pooling'],'Design the edge path for a global media site.','Request-path diagram with failure and trust boundaries.'),
U('compute-patterns','Compute and worker patterns','deep','Choose stateless services, stateful nodes, workers, schedulers, serverless and batch.',['stateless','stateful','worker pool','job runner','scheduler','autoscaling','serverless','batch'],'Map six workloads to compute patterns and explain cold start, state and scale concerns.','Decision table with workload fit.'),
U('data-primitive-selection','Data primitive selection','architect','Choose storage from access patterns and guarantees rather than popularity.',['relational','key-value','document','wide-column','graph','search','object','time-series','vector','warehouse'],'Assign profile, feed, graph, media, search and analytics data to stores.','Polyglot persistence map with consistency and ownership rationale.'),
U('async-cache-coordination','Caching, asynchronous work & coordination placement','architect','Know when latency, load and decoupling justify cache, queue, log or coordination systems.',['cache','queue','pub/sub','distributed log','outbox','lock','lease','idempotency','backpressure'],'Refactor a synchronous monolith under a 500ms downstream dependency and bursty traffic.','Revised architecture with correctness risks called out.')]),
M('failure-design','Failure-oriented system design','Design by asking how dependencies fail, what users observe and how the system recovers.','Architecture quality is exposed during partial failure, overload and recovery.',[],['design-method'],['google-sre','aws-retries','jepsen'],[
U('dependency-failure-map','Dependency failure mapping','deep','Enumerate timeout, error, slow, stale, duplicate and unavailable states.',['failure mode','timeout','slow dependency','partial response','stale data','retry amplification','fallback'],'Create a dependency failure matrix for checkout with payment, inventory and notification services.','Failure matrix mapping user impact to mitigation.'),
U('overload-degradation','Overload & graceful degradation','architect','Protect core journeys when demand exceeds capacity.',['admission control','load shedding','priority','brownout','queue cap','backpressure','feature degradation'],'Design overload behavior for search where autocomplete may fail before core results.','Degradation ladder tied to SLOs.'),
U('recovery-reconciliation','Recovery, replay & reconciliation','architect','Specify how the system becomes correct after partial failure.',['replay','repair','reconciliation','backfill','deduplication','compensation','audit','operator tooling'],'Recover an order workflow after a 20-minute event-consumer outage and duplicate redelivery.','Recovery runbook and invariant checks.')],90),
M('global-design','Global, multi-region & regulated system design','Make explicit choices about regional placement, routing, replication and sovereignty.','Global systems trade latency and availability against consistency, cost and regulation.',['multi-region'],[],['gcp-arch','aws-wa','ddia'],[
U('global-routing','Global traffic routing & locality','deep','Keep users near compute while maintaining safe failover.',['GeoDNS','anycast concept','global load balancing','latency routing','health routing','home region','sticky region'],'Design routing for EU, India and US users with per-tenant residency.','Routing/data-locality diagram with failover paths.'),
U('global-data','Global data placement & consistency','architect','Choose active-passive, active-active, quorum or home-region models per workload.',['active-active','active-passive','replication lag','conflict','quorum','home region','read local/write leader'],'Compare profile data, chat messages and payment ledger placement.','Per-dataset consistency and placement matrix.'),
U('residency-failover','Residency-aware failover','architect','Fail safely without violating where data may live.',['data residency','regional evacuation','backup region','encryption domain','routing guardrail','RTO/RPO'],'Plan EU-region evacuation when tenant data may not leave EU.','DR plan preserving residency constraints.')]),
M('design-evolution','Evolution from V1 to hyperscale','Practice architecture as a sequence of reversible steps rather than a single end state.','Staff engineers know what not to build yet and what signals justify complexity.',[],['design-method'],['martin-fowler','ddia','google-sre'],[
U('v1-minimum','Minimum viable architecture','deep','Prefer the simplest architecture that meets current constraints while preserving critical seams.',['modular monolith','managed database','vertical scale','simple cache','operational simplicity'],'Design a 10k-user work-management SaaS with a small team.','V1 architecture with explicit deferred complexity.'),
U('scale-trigger','Scale-triggered evolution','architect','Tie architectural changes to measurable thresholds.',['trigger metric','capacity ceiling','team ownership','failure cost','data volume','operational load'],'For each potential microservice, cache or shard, define the signal that justifies it.','Evolution decision table with thresholds.'),
U('migration-plan-design','Safe architecture migration plan','architect','Evolve without big-bang rewrites using compatibility, shadowing and rollback.',['strangler','dual read','dual write risk','shadow traffic','backfill','reconciliation','rollback'],'Move one module from monolith to service while users stay online.','Phased migration sequence with safety checks.')]),
M('design-lab','Progressive system design lab','Build architecture judgment by repeatedly designing complete systems and changing constraints.','Patterns become useful when you can compose them under ambiguous requirements and defend the result.',['system-design-method'],['design-method','building-blocks'],['ddia','google-sre','gcp-arch','aws-wa'],[
...[
['url-shortener','URL shortener','foundation',['IDs','redirect latency','hot keys','abuse','TTL']],['rate-limiter','Distributed rate limiter','deep',['token bucket','distributed state','clock','fairness','fail-open/closed']],['notifications','Notification platform','deep',['preferences','fan-out','queueing','retry','dedup','provider failure']],['scheduler','Distributed job scheduler','deep',['lease','ownership','misfire','retry','partition','clock']],['distributed-cache','Distributed cache','architect',['partitioning','replication','eviction','consistency','hot keys','failure']],['autocomplete','Search autocomplete','deep',['prefix index','ranking','freshness','cache','latency']],['chat','Chat & presence','architect',['WebSocket','fan-out','ordering','offline','presence','multi-device']],['collaboration','Slack/Jira-style collaboration','architect',['multi-tenancy','permissions','search','events','notifications','audit']],['feed','Social/news feed','architect',['fan-out on write/read','ranking','celebrity problem','cache','pagination']],['drive','Dropbox/Drive','architect',['chunking','metadata','object storage','sync','dedup','conflict']],['video','Video streaming','architect',['upload','transcode','CDN','manifest','adaptive bitrate','rights']],['ride-hailing','Ride hailing','architect',['geospatial','matching','location stream','ETA','consistency','surge']],['booking','Ticket/seat booking','architect',['inventory','holds','contention','expiry','payment','oversell prevention']],['payments','Payments & ledger','architect',['idempotency','ledger','double-entry','reconciliation','webhooks','compliance']],['collab-editor','Collaborative editor','architect',['OT','CRDT','presence','offline','causality','snapshots']],['log-platform','Logging/metrics platform','architect',['ingest','partition','retention','index','aggregation','cardinality']],['search-engine','Search engine','architect',['crawl/index','inverted index','shards','ranking','freshness','query serving']],['feature-flags','Feature flag platform','deep',['control plane','data plane','SDK cache','streaming updates','targeting','audit']],['api-gateway','API gateway','architect',['routing','auth','limits','observability','config rollout','multi-region']],['identity','Identity & authorization platform','architect',['SSO','sessions','tokens','policy','directory','audit']],['workflow','Workflow engine','architect',['durable state','timers','replay','activities','retry','versioning']],['saas-control','Multi-tenant SaaS control plane','architect',['tenant provisioning','isolation','quotas','billing','residency','migration']]
].map(x=>caseUnit(...x))],60)
]};

const ai={id:'ai-systems',phase:6,order:14,title:'AI Systems, RAG, Agents & AI Platform Architecture',summary:'Build AI-enabled products as engineered systems with retrieval, tools, state, evals, security, observability and cost control.',modules:[
M('llm-runtime','LLM application runtime fundamentals','Understand model I/O, context, structured output, streaming, latency and failure behavior before orchestration.','AI applications still need explicit contracts, budgets and error handling.',['llm-foundations'],[],['openai-dev','anthropic-docs'],[
U('model-interface','Model APIs, messages & structured outputs','working','Treat model interaction as a typed external dependency.',['messages','roles','structured output','schema validation','streaming','tool call envelope','finish reason'],'Build one feature that returns schema-validated data and handles malformed or partial outputs.','Typed adapter with validation and tests.'),
U('context-budget','Tokens, context windows & context budgeting','deep','Reason about finite context as a resource with relevance, cost and latency consequences.',['tokenization','context window','prompt size','output budget','truncation','context selection','summarization'],'Measure quality, latency and cost as context grows.','Experiment report with context policy.'),
U('model-routing','Model selection, routing & fallback','architect','Route work by capability, latency, cost, privacy and availability.',['model capability','routing','fallback','tiering','latency budget','cost budget','regional availability'],'Design a gateway that routes classification, reasoning and bulk extraction differently.','Routing policy and failure strategy.')],30),
M('context-engineering','Context engineering & prompt/program design','Build deterministic scaffolding around probabilistic models.','Production quality comes from context, tools, constraints and evaluation, not prompt cleverness alone.',[],['llm-runtime'],['openai-dev','anthropic-docs'],[
U('prompt-contracts','Prompt contracts & versioning','deep','Treat system instructions and examples as versioned program assets.',['system instruction','few-shot','prompt template','version','input contract','output contract','regression'],'Version a prompt through three behavior changes while preserving tests.','Prompt changelog and eval diff.'),
U('context-assembly','Dynamic context assembly','architect','Select only relevant policies, user state, retrieved facts and tool affordances.',['context source','priority','deduplication','recency','authority','compression','provenance'],'Build a context builder for a coding assistant with repo docs, task and policy constraints.','Context trace showing why each chunk was included.'),
U('prompt-caching','Prompt/context caching','architect','Reduce repeated latency or cost without serving semantically stale context.',['prefix caching','semantic cache','cache key','tenant boundary','freshness','invalidation','privacy'],'Design caching for repeated enterprise-agent instructions and shared repo context.','Cache policy with correctness and isolation analysis.')],30),
M('retrieval-ingestion','Retrieval ingestion & knowledge preparation','Build reliable, updateable corpora for RAG.','Retrieval quality is bounded by ingestion quality, structure and freshness.',['rag-retrieval'],[],['openai-dev','opensearch-vector'],[
U('chunking-structure','Chunking & document structure','deep','Preserve semantic units and hierarchy rather than arbitrary token windows.',['chunking','section hierarchy','overlap','tables','code','metadata','parent-child'],'Compare fixed, semantic and structure-aware chunking on architecture docs.','Retrieval benchmark by chunking strategy.'),
U('index-pipeline','Indexing, updates & deletion','deep','Keep vector and text indexes synchronized with source truth.',['ingestion','embedding','upsert','delete','version','CDC','freshness','tombstone'],'Implement incremental updates and prove deleted content disappears.','Ingestion pipeline with freshness and deletion tests.'),
U('knowledge-boundaries','Tenant/security-aware retrieval','architect','Enforce authorization before or during retrieval, never as a display filter.',['ACL','tenant filter','document permission','security trimming','metadata filter','side channel'],'Design retrieval across private org and project docs.','Threat model and access-control tests.')],30),
M('retrieval-quality','Hybrid retrieval, reranking & grounded generation','Optimize retrieval with measurable relevance.','Vector similarity alone is rarely sufficient for production search or RAG.',['rag-retrieval'],['retrieval-ingestion'],['stanford-ir','opensearch-vector','openai-dev'],[
U('hybrid-retrieval','Lexical + vector hybrid retrieval','deep','Combine exact term matching and semantic recall.',['BM25','vector similarity','hybrid fusion','metadata filter','query rewrite','candidate set'],'Compare lexical, vector and hybrid retrieval on a 50-query set.','Recall and precision comparison with failure taxonomy.'),
U('reranking','Reranking & query transformation','deep','Spend more compute on a small candidate set to improve relevance.',['cross-encoder concept','LLM reranker','reciprocal rank fusion','query decomposition','multi-query'],'Add reranking and measure when it helps or hurts.','Before and after relevance report.'),
U('grounding-citations','Grounding, citations & answerability','architect','Teach the product to abstain or cite when evidence is insufficient.',['grounding','citation','provenance','answerability','abstention','conflict resolution'],'Create conflicting or stale documents and test answer behavior.','Grounded-answer policy plus eval cases.')],30),
M('agent-orchestration','Agentic workflows & tool orchestration','Design agents as bounded workflows with state, tools and explicit stop conditions.','An agent loop without control surfaces becomes expensive, unsafe and hard to debug.',['agentic-systems'],[],['openai-dev','anthropic-agents'],[
U('workflow-vs-agent','Workflow vs agent decision','deep','Use deterministic workflow when the path is known and agents when model judgment is necessary.',['workflow','agent loop','branching','planner','router','handoff','bounded autonomy'],'Classify ten AI tasks as workflow, agent or hybrid and justify.','Decision rubric with examples.'),
U('tool-contracts','Tool contracts, permissions & idempotency','architect','Make tools safe external capabilities with typed inputs and side-effect semantics.',['tool schema','permission','side effect','idempotency','confirmation','timeout','retry','result validation'],'Wrap issue creation, code search and deployment tools with different authority levels.','Tool registry with authority and retry policy.'),
U('agent-state','Agent state, checkpoints & resumability','architect','Persist durable workflow state rather than relying on hidden conversational context.',['state machine','checkpoint','resume','event log','task state','handoff','memory separation'],'Crash an agent mid-task and resume without repeating side effects.','State model and recovery test.'),
U('multi-agent','Multi-agent decomposition & handoffs','architect','Use multiple agents only when specialization or parallelism beats coordination cost.',['specialist','handoff','shared state','task graph','parallelism','merge','conflict'],'Compare single-agent and specialist-agent implementations of a research plus coding task.','Quality, cost and latency comparison.')],21),
M('memory-context','Memory systems for AI products','Separate ephemeral context, durable user memory, task state and knowledge stores.','Calling every persistence mechanism memory creates privacy and correctness failures.',[],['agent-orchestration'],['openai-dev','anthropic-docs'],[
U('memory-taxonomy','Memory taxonomy & lifecycle','deep','Define what is remembered, why, for how long and with whose authority.',['working memory','episodic memory','semantic memory','user preference','task state','knowledge base','TTL','deletion'],'Design memory for a coding assistant without retaining secrets or stale task assumptions.','Memory policy matrix.'),
U('memory-retrieval','Memory write/read policies','architect','Write only high-value facts and retrieve them with provenance and freshness.',['write gate','confidence','source','recency','dedup','conflict','forget'],'Simulate conflicting remembered preferences and resolve them.','Conflict and freshness policy.'),
U('shared-memory','Team/repo shared memory & knowledge graph patterns','architect','Model shared engineering context with ownership, provenance and update mechanisms.',['repo memory','team memory','entity relation','knowledge graph','source map','ownership','write-back'],'Design cross-session repo knowledge without hidden stale summaries.','Schema plus update and reconciliation flow.')],45),
M('ai-evaluation','AI evaluation & quality engineering','Measure nondeterministic behavior using datasets, rubrics and production signals.','Without evals, every prompt, model or retrieval change is an uncontrolled release.',['ai-evals'],[],['openai-dev'],[
U('eval-datasets','Evaluation datasets & failure taxonomies','deep','Represent critical behavior and known failures with traceable cases.',['golden set','synthetic case','production sample','failure label','slice','coverage','data leakage'],'Build a 100-case suite across normal, edge, adversarial and historical failures.','Versioned eval dataset with taxonomy.'),
U('eval-metrics','Task, retrieval, tool & agent metrics','deep','Use metrics matched to the system layer.',['exactness','rubric','retrieval recall','MRR concept','tool success','trajectory','latency','cost'],'Define layer-specific metrics for a RAG agent.','Metric specification and thresholds.'),
U('judges-human','LLM judges & human review','architect','Calibrate automated judges against humans and handle disagreement.',['judge prompt','bias','position effect','pairwise','rubric','human calibration','confidence'],'Compare judge scores with human labels on 50 cases.','Calibration report.'),
U('online-evals','Online monitoring & regression gates','architect','Connect offline quality to production telemetry and release controls.',['canary','A/B','quality drift','shadow eval','regression gate','rollback'],'Design an AI release pipeline that blocks quality regressions.','Release gate design.')],21),
M('ai-security','AI security, governance & human control','Treat model inputs, retrieved content and tools as untrusted at explicit trust boundaries.','AI adds new injection and authority-transfer paths on top of normal application security.',['ai-security-governance'],[],['owasp-llm','nist-ai'],[
U('prompt-injection','Direct and indirect prompt injection','deep','Assume untrusted content can attempt to rewrite agent behavior.',['direct injection','indirect injection','instruction/data separation','trusted channel','content isolation'],'Attack an agent through a retrieved document and harden its control plane.','Attack and mitigation test suite.'),
U('tool-abuse','Tool abuse & confused-deputy prevention','architect','Prevent model-controlled data from escalating into unauthorized side effects.',['least privilege','capability','confirmation','allowlist','resource scope','confused deputy'],'Design safe repo, ticket and shell tools for an engineering agent.','Authority matrix and approval policy.'),
U('data-exfiltration','Sensitive-data leakage & model boundary','architect','Control what data may enter prompts, tools, logs and external model endpoints.',['PII','secret','redaction','DLP concept','tenant isolation','model provider boundary','logging'],'Threat-model a customer-support copilot with regulated data.','Data-flow and retention controls.'),
U('human-control','Human approval, audit & governance','architect','Place human checkpoints based on consequence and reversibility.',['approval threshold','four-eyes','audit log','policy exception','model change review','risk tier'],'Define autonomous vs approval-required actions for an enterprise agent.','Governance matrix.')],21),
M('ai-platform','AI platform, harness & runtime architecture','Build reusable AI infrastructure that centralizes policy while preserving product-team velocity.','Organizations need consistent model access, tools, context, evals and controls rather than each team rebuilding them.',['ai-platform-architecture'],[],['openai-dev','otel','cncf'],[
U('model-gateway','Model gateway, routing & budgets','architect','Centralize provider abstraction, policy, routing and usage control.',['gateway','provider adapter','routing','rate limit','budget','fallback','region','audit'],'Design a multi-provider enterprise model gateway.','Architecture plus routing and policy specification.'),
U('tool-registry','Tool/plugin registry & capability platform','architect','Discover and govern reusable tools with ownership and permission metadata.',['tool registry','plugin','capability','schema','owner','version','permission','health'],'Design registry onboarding, deprecation and runtime authorization.','Registry schema and lifecycle.'),
U('sandbox-runtime','Sandboxed execution & agent runtime','architect','Isolate untrusted code and tools with explicit CPU, network, filesystem and secret boundaries.',['sandbox','container','microVM concept','filesystem','network egress','secret injection','timeout','resource limit'],'Design code-execution sandboxes for coding agents.','Threat model and runtime policy.'),
U('trace-eval-store','Trace, eval & feedback data plane','architect','Persist model and tool trajectories for debugging, evaluation and governance.',['trace','span','prompt version','tool call','token usage','feedback','eval result','retention'],'Design trace storage for high-volume enterprise agents.','Trace schema and retention/cost plan.'),
U('ai-harness','End-to-end AI harness architecture','architect','Compose model gateway, context, memory, retrieval, tools, policy, sandbox, eval and observability layers.',['harness','context service','memory service','retrieval service','policy engine','tool runtime','eval service','trace service'],'Design a Claude-Code-like enterprise harness supporting multiple coding agents.','Reference architecture plus failure and scaling analysis.')],30)
]};

const leadership={id:'staff-leadership',phase:7,order:15,title:'Staff/Principal Engineering & Technical Leadership',summary:'Multiply engineering impact through technical strategy, decision quality, mentoring, reviews, cross-team systems and organizational leverage.',modules:[
M('design-review-leadership','Architecture & design review leadership','Run reviews that expose assumptions and risks without becoming gatekeeping theater.','Staff engineers improve decisions across teams, not just their own code.',['technical-leadership','architecture-docs'],[],['google-eng-practices','staffeng','martin-fowler'],[
U('review-framing','Frame a design review','deep','Identify decision scope, irreversible choices, required evidence and reviewers.',['decision scope','review goal','stakeholder','risk','evidence','pre-read'],'Prepare a review for adopting event sourcing in one bounded context.','Review brief and reviewer map.'),
U('review-questioning','High-leverage architecture questions','architect','Probe invariants, failure, ownership, migration and operations rather than syntax preferences.',['assumption','invariant','failure mode','capacity','security','operability','migration','ownership'],'Review a flawed microservice proposal and identify the five most consequential questions.','Annotated design with ranked concerns.'),
U('decision-closure','Close decisions with records and conditions','architect','Capture decision, alternatives, dissent and revisit triggers.',['ADR','decision owner','dissent','condition','follow-up','revisit trigger'],'Turn an ambiguous review discussion into an actionable decision.','ADR plus unresolved-risk register.')]),
M('technical-strategy','Technical strategy & multi-quarter direction','Connect product direction to capabilities, architecture evolution, platform investments and risk reduction.','Principal engineers shape sequences of decisions, not isolated designs.',['technical-leadership'],[],['staffeng','team-topologies','gcp-arch'],[
U('strategy-thesis','Technical strategy thesis','architect','State the few technical bets and constraints that should guide many teams.',['strategy','capability','constraint','principle','bet','risk','differentiator'],'Write a technical strategy for a SaaS product moving from regional SMB to global enterprise.','Three-page strategy with explicit non-goals.'),
U('capability-roadmap','Capability-based architecture roadmap','architect','Sequence capabilities and migrations around dependencies and decision gates.',['capability','milestone','dependency','decision gate','migration','platform investment'],'Build a roadmap for identity, multi-tenancy, search and regionalization.','Capability roadmap with gates.'),
U('risk-portfolio','Technical risk portfolio','architect','Manage systemic risks across reliability, security, data and delivery.',['risk','likelihood','impact','leading indicator','mitigation','owner','residual risk'],'Create a risk register for the capstone at scale.','Prioritized portfolio with mitigation economics.')]),
M('cross-team-influence','Cross-team influence & alignment','Drive decisions through shared context, interfaces and incentives rather than authority.','Large-system architecture is a social and organizational system as much as a codebase.',['technical-leadership'],[],['staffeng','team-topologies'],[
U('stakeholder-mapping','Technical stakeholder mapping','deep','Understand who owns decisions, constraints and operational consequences.',['stakeholder','decision rights','dependency','incentive','operator','consumer'],'Map stakeholders for a shared authorization platform.','Stakeholder and decision map.'),
U('alignment-artifacts','Alignment through RFCs, prototypes & data','architect','Choose artifacts that reduce disagreement fastest.',['RFC','prototype','benchmark','experiment','migration demo','decision log'],'Resolve a REST-versus-events dispute with the minimum evidence needed.','Decision evidence package.'),
U('influence-without-authority','Influence without authority','architect','Create adoption through value, defaults and trust rather than mandates.',['paved road','opt-in','incentive','migration support','exception process','credibility'],'Design adoption strategy for a new platform API across five teams.','Adoption plan with escape hatches.')]),
M('engineering-execution','Large technical initiative execution','Decompose ambiguous multi-team work into bounded increments with feedback and demoable checkpoints.','Unsafe sequencing creates migration and operational risk.',[],[],['staffeng','google-eng-practices'],[
U('decomposition','Decompose architecture programs','architect','Split by learning and risk milestones rather than layer silos.',['vertical slice','risk spike','dependency','milestone','critical path','integration'],'Decompose a multi-region migration into demoable checkpoints.','Program map with dependency and risk sequencing.'),
U('uncertainty-burndown','Decision cadence & uncertainty burn-down','architect','Front-load unknowns that could invalidate the plan.',['unknown','spike','prototype','decision deadline','reversible step','feedback'],'Plan a database migration where scale behavior is uncertain.','Uncertainty burn-down plan.'),
U('delivery-health','Technical delivery health signals','deep','Track architecture work with leading signals, not percent-complete fiction.',['integration status','risk trend','SLO','migration coverage','adoption','defect','toil'],'Define health metrics for platform rollout.','Scorecard with action thresholds.')]),
M('mentoring-standards','Mentoring, standards & engineering quality systems','Scale judgment through people, review norms and lightweight standards.','The goal is consistently strong decisions and lower cognitive load, not uniformity.',['technical-leadership'],[],['google-eng-practices','staffeng'],[
U('mentoring-model','Mentoring technical judgment','deep','Teach reasoning via questions, counterexamples and progressively harder ownership.',['coaching','delegation','feedback','design critique','ownership','growth'],'Create a growth path from senior engineer to architecture owner.','Competency rubric and coaching plan.'),
U('standards-governance','Engineering standards & exception processes','architect','Set minimum safety and compatibility standards without freezing innovation.',['standard','guardrail','exception','sunset','ownership','automation','waiver'],'Define API and production-readiness standards with an exception path.','Standard plus automated checks plus exception template.'),
U('review-culture','Code and design review culture','deep','Optimize reviews for correctness, learning and maintainability rather than style dominance.',['review latency','scope','blocking issue','nit','ownership','learning'],'Audit a team review process and reduce cycle time without lowering quality.','Review-policy redesign.')],180),
M('incident-leadership','Incident & resilience leadership','Lead technical response under ambiguity and convert incidents into systemic improvement.','Principal engineers are trusted when architecture assumptions fail in real time.',[],[],['google-sre','staffeng'],[
U('incident-command','Technical incident command','architect','Maintain shared reality, priorities and safe decision-making during outages.',['incident commander','operations lead','communications','timeline','hypothesis','mitigation','rollback'],'Run a simulated cascading dependency outage.','Incident timeline and command decisions.'),
U('post-incident-investment','Convert incidents into engineering investment','architect','Separate local fixes from systemic contributors and portfolio-level risks.',['contributing factor','systemic cause','guardrail','automation','capacity','ownership'],'Turn three recurring incidents into a reliability investment proposal.','Prioritized action portfolio with expected risk reduction.')]),
M('architecture-economics-leadership','Engineering economics & build/buy/platform decisions','Frame technical choices in terms of lifecycle cost, opportunity cost and strategic differentiation.','Architectural elegance without economic context is not product architecture.',[],[],['staffeng'],[
U('lifecycle-cost','Lifecycle cost & opportunity cost','architect','Include staffing, operations, migration, security and switching cost.',['TCO','opportunity cost','maintenance','on-call','vendor cost','switching cost','migration cost'],'Compare self-hosted Kafka versus managed streaming for a small and large organization.','Five-year cost and risk model.'),
U('platform-investment','Platform investment economics','architect','Know when repeated team pain justifies shared infrastructure.',['repetition','cognitive load','platform fixed cost','adoption','marginal benefit','internal customer'],'Decide whether to build an internal developer platform.','Investment thesis with adoption threshold.')],180)
]};

const electives={id:'advanced-electives',phase:7,order:16,title:'Advanced & Specialized Engineering Electives',summary:'Broaden architectural range into specialist domains that prevent blind spots when unusual constraints appear.',modules:[
M('pl-compilers','Programming languages, type systems & compiler/runtime concepts','Understand how languages turn source into executable behavior and how type/runtime choices affect systems.','Architects benefit from knowing what language and runtime guarantees actually mean.',[],[],['cs2023','csapp'],[
U('language-semantics','Language semantics & type-system concepts','working','Understand static/dynamic typing, soundness trade-offs, variance and effects conceptually.',['static/dynamic','nominal/structural','type inference','variance','nullability','soundness','effect concept'],'Compare Java, TypeScript and Rust type guarantees for API-domain code.','Comparison memo focused on failure classes.'),
U('compiler-pipeline','Compiler/interpreter pipeline','working','Know lex, parse, IR, optimization, codegen and JIT at a high level.',['lexer','parser','AST','IR','optimization','code generation','interpreter','JIT'],'Trace a small expression through a toy compiler or interpreter.','Pipeline diagram and implementation notes.'),
U('runtime-abi','Runtime, ABI & FFI concepts','deep','Understand native boundaries and runtime interoperability risks.',['ABI','FFI','native library','memory ownership','serialization boundary','GC interaction'],'Design a Java service calling a native ML library safely.','Boundary risk analysis.')],240),
M('parallel-gpu','Parallel computing & GPU architecture concepts','Understand when workloads benefit from data parallelism and how GPU constraints differ from server concurrency.','AI, data and graphics systems introduce hardware execution models unfamiliar to backend engineers.',[],[],['cs2023'],[
U('parallel-models','Parallel execution models','working','Distinguish task parallelism, data parallelism and vectorization.',['SIMD','MIMD','task parallelism','data parallelism','Amdahl’s Law','memory bandwidth'],'Estimate theoretical speedup for a parallel workload.','Speedup model and bottleneck explanation.'),
U('gpu-model','GPU execution & memory hierarchy concepts','working','Understand kernels, thread groups, warps and host/device memory at architectural depth.',['kernel','thread block','warp concept','device memory','shared memory','transfer cost'],'Explain why a workload can be GPU-slower despite massive parallelism.','Performance reasoning memo.')],240),
M('mobile-offline','Mobile, offline-first & edge-client architecture','Design products for intermittent networks, constrained devices and background execution.','Desktop-web assumptions break on mobile clients and edge devices.',[],[],['mdn'],[
U('offline-sync','Offline-first data synchronization','deep','Queue local mutations and reconcile with server state after reconnect.',['local database','sync queue','version','conflict','merge','tombstone','retry'],'Design offline task editing across two devices.','Sync state machine and conflict cases.'),
U('mobile-background','Mobile background execution & push concepts','working','Account for platform suspension, battery and notification-driven wakeups.',['background limit','push notification','sync window','battery','connectivity','resume'],'Design reliable mobile notification and update behavior.','Client lifecycle diagram.'),
U('edge-client-security','Client trust & device security boundaries','deep','Treat client state and binaries as observable and tamperable.',['untrusted client','secure storage concept','attestation concept','API authorization','secret avoidance'],'Threat-model a mobile app holding refresh tokens.','Threat model and storage policy.')],180),
M('wasm-edge','WebAssembly & edge runtime concepts','Understand portable sandboxed compute and where edge execution changes latency and trust boundaries.','Modern product architecture increasingly includes browser, edge and sandbox runtimes.',[],[],['mdn','cncf'],[
U('wasm-model','WebAssembly execution model','working','Understand modules, linear memory, host imports and sandbox boundaries.',['Wasm module','linear memory','host import','sandbox','WASI concept'],'Run or inspect a simple Wasm module and map host capabilities.','Capability-boundary diagram.'),
U('edge-runtime','Edge compute/runtime trade-offs','deep','Place lightweight compute near users without ignoring state, consistency and observability.',['edge worker','cold start','regional state','global KV','consistency','egress'],'Move a personalization function to the edge and critique the choice.','Latency, correctness and cost trade-off memo.')],180),
M('privacy-crypto-advanced','Advanced privacy & cryptographic architecture concepts','Recognize specialized privacy techniques and when expert review is mandatory.','Architects should know the vocabulary and limits even when specialists implement the solution.',[],[],['owasp-crypto'],[
U('privacy-enhancing-tech','Privacy-enhancing technology concepts','working','Understand anonymization limits and high-level PET categories.',['pseudonymization','anonymization','k-anonymity limitation','differential privacy concept','secure computation concept'],'Evaluate an analytics dataset claimed to be anonymous.','Privacy-risk memo.'),
U('crypto-protocol-boundaries','Cryptographic protocol design boundaries','deep','Know why custom crypto and protocol design require specialist review.',['nonce','replay','key agreement concept','forward secrecy','authenticated encryption','protocol composition'],'Review a proposed custom token-encryption scheme and identify design risks.','Escalation checklist to security or crypto specialists.')],240),
M('domain-specific-architecture','Domain-specific architecture survey','Learn the distinctive invariants that make certain industries architecturally different.','Product architects need enough vocabulary to recognize when generic web patterns are insufficient.',[],[],['swebok4'],[
U('financial-systems','Financial and ledger system concepts','working','Understand immutable ledgers, reconciliation, settlement and audit as architectural drivers.',['double-entry','ledger','reconciliation','settlement','idempotency','audit'],'Model money movement between wallets and external bank rails.','Invariant and reconciliation design.'),
U('iot-edge','IoT and device-fleet concepts','working','Reason about intermittently connected devices, telemetry, commands and fleet management.',['device identity','telemetry','command','offline','firmware update','fleet'],'Design a sensor fleet sending telemetry over unreliable networks.','Device and cloud architecture diagram.'),
U('gaming-realtime','Realtime multiplayer/game backend concepts','working','Understand authoritative state, update loops and latency compensation at high level.',['authoritative server','tick','latency','matchmaking','state replication','cheat boundary'],'Design a simple realtime multiplayer lobby and match service.','Latency and state-ownership memo.')],240)
]};

export default [systemDesign,ai,leadership,electives];
