import { ArrowLeft, Bookmark, BookmarkCheck, Check, CheckCircle2, Copy, ExternalLink, Target, Trophy } from 'lucide-react';
import type { LearningUnit, MasteryModes, V2Domain, V2Module } from '../types';
import { copy, curriculumDriftPrompt, depthLabel, freshness, moduleResources } from './data';

type Progress={state:{bookmarkedModules:string[]};getUnit:(id:string)=>{modes:MasteryModes;evidence:string;notes:string};setMode:(id:string,key:keyof MasteryModes,value:boolean)=>void;setEvidence:(id:string,v:string)=>void;setNotes:(id:string,v:string)=>void;isComplete:(id:string)=>boolean;toggleModuleBookmark:(id:string)=>void};
export default function Detail({domain,module,unit,progress,back,openUnit}:{domain:V2Domain;module:V2Module;unit?:LearningUnit;progress:Progress;back:()=>void;openUnit:(u:LearningUnit)=>void}){
  const refs=moduleResources(module);
  if(!unit)return <><button className="v2-back" onClick={back}><ArrowLeft size={14}/> Curriculum</button><header className="v2-page-head split"><div><span className="eyebrow">{domain.title}</span><h1>{module.title}</h1><p>{module.summary}</p></div><button className="v2-icon" onClick={()=>progress.toggleModuleBookmark(module.id)}>{progress.state.bookmarkedModules.includes(module.id)?<BookmarkCheck/>:<Bookmark/>}</button></header>
    <section className="v2-callout"><Target size={19}/><div><strong>Why this exists</strong><p>{module.why}</p></div></section>
    {module.prerequisites.length>0&&<section className="v2-mini"><span className="eyebrow">PREREQUISITES</span><div className="v2-chips">{module.prerequisites.map(p=><span key={p}>{p}</span>)}</div></section>}
    <section className="v2-mini"><span className="eyebrow">LEARNING UNITS</span><h2>Complete each with evidence</h2><div className="v2-unit-list">{module.units.map((u,i)=><button key={u.id} className={progress.isComplete(u.id)?'done':''} onClick={()=>openUnit(u)}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{u.title}</strong><small>{u.summary}</small></div><em className={`v2-depth ${u.depth}`}>{depthLabel[u.depth]}</em>{progress.isComplete(u.id)&&<CheckCircle2 size={16}/>}</button>)}</div></section>
    <Resources refs={refs}/><section className="v2-card v2-maint"><span className="eyebrow">CURRICULUM MAINTENANCE</span><h3>{freshness(module.lastReviewed,module.curriculumReviewEveryDays).label}</h3><p>Last curriculum review: {module.lastReviewed}. Review every {module.curriculumReviewEveryDays} days.</p><button className="v2-btn compact" onClick={()=>copy(curriculumDriftPrompt(domain,module))}><Copy size={13}/> Copy curriculum drift task</button></section></>;

  const p=progress.getUnit(unit.id);const modes:[keyof MasteryModes,string][]=[['understand','Understand'],['implement','Implement'],['breakIt','Break'],['measure','Measure'],['explain','Explain']];
  return <><button className="v2-back" onClick={back}><ArrowLeft size={14}/> {module.title}</button><header className="v2-page-head split"><div><span className="eyebrow">{domain.title} · {module.title}</span><h1>{unit.title}</h1><p>{unit.summary}</p></div><span className={`v2-depth big ${unit.depth}`}>{depthLabel[unit.depth]}</span></header>
    <div className="v2-unit-layout"><div><section className="v2-card"><span className="eyebrow">CONCEPT INVENTORY</span><div className="v2-concepts">{unit.concepts.map(c=><span key={c}>{c}</span>)}</div></section><section className="v2-card challenge"><span className="eyebrow">PRACTICAL CHALLENGE</span><h2>Build or investigate this</h2><p>{unit.challenge}</p></section><Resources refs={refs}/></div>
      <aside className="v2-mastery"><span className="eyebrow">MASTERY EVIDENCE</span><h2>Prove it.</h2><p>A unit only counts after all five modes and a concrete artifact.</p><div className="v2-modes">{modes.map(([k,label])=><label key={k}><input type="checkbox" checked={p.modes[k]} onChange={e=>progress.setMode(unit.id,k,e.target.checked)}/><span>{label}</span>{p.modes[k]&&<Check size={14}/>}</label>)}</div><label className="v2-field"><span>Evidence</span><textarea value={p.evidence} onChange={e=>progress.setEvidence(unit.id,e.target.value)} placeholder={unit.evidence}/></label><label className="v2-field"><span>Notes / trade-offs learned</span><textarea value={p.notes} onChange={e=>progress.setNotes(unit.id,e.target.value)} placeholder="What failed? What changed your mental model? When would another design win?"/></label><div className={`v2-complete ${progress.isComplete(unit.id)?'yes':''}`}>{progress.isComplete(unit.id)?<><Trophy size={17}/> Mastered</>:<>Complete five modes + evidence</>}</div></aside></div></>;
}
function Resources({refs}:{refs:ReturnType<typeof moduleResources>}){return <section className="v2-card"><span className="eyebrow">BEST RESOURCES</span><h2>Curated starting set</h2><div className="v2-resources">{refs.map(r=>{const f=freshness(r.lastVerified,r.refreshEveryDays);return <a href={r.url} target="_blank" rel="noreferrer" key={r.id}><div><strong>{r.title}</strong><small>{r.kind} · {r.role}</small></div><em className={`v2-fresh ${f.tone}`}>{f.label}</em><ExternalLink size={13}/></a>})}</div></section>}
